name: farmacia2pdm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.2.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  google_maps_flutter: ^2.2.6
  google_maps_flutter_web: ^0.5.0
  geolocator: ^11.0.0
  permission_handler: ^11.3.0
  google_maps_apis: ^3.0.1
  shared_preferences: ^2.2.2
  intl: ^0.18.0
  camera: ^0.10.5
  image_picker: ^0.8.7



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/logo.png
